import { config } from '../../config'
import BreadcrumbSchema from '../../components/BreadcrumbSchema'

export const metadata = {
  // Title under 60 chars and front-loaded with the keyword + region. The
  // service-radius factoid was eating SERP real estate without helping
  // ranking.
  title: 'Dumpster Rental Service Area in Southern IL',
  description: `${config.businessName} delivers dumpsters across ${config.serviceTowns.length}+ towns in Southern Illinois — ${config.serviceTowns.slice(0, 5).join(', ')}, and more. Same-day delivery from $${config.dumpsters[0].pricing['10-day']}. Call ${config.phone}.`,
  // Surface every served town as a keyword so the page can pick up the
  // long-tail "[town] IL dumpster rental" queries.
  keywords: config.serviceTowns.slice(0, 30).map(t => `dumpster rental ${t} IL`),
  alternates: { canonical: `${config.websiteUrl}/service-area` },
  openGraph: {
    title: 'Dumpster Rental Service Area in Southern IL',
    description: `${config.serviceTowns.length}+ towns served. Same-day delivery, locally owned.`,
    url: `${config.websiteUrl}/service-area`,
    siteName: config.businessName,
    locale: 'en_US',
    type: 'website',
    // OG image auto-generated by ./opengraph-image.jsx
  },
}

export default function ServiceAreaLayout({ children }) {
  return (
    <>
      <BreadcrumbSchema items={[{ name: 'Service Area', path: '/service-area' }]} />
      {children}
    </>
  )
}
