import { config } from '../../config'
import BreadcrumbSchema from '../../components/BreadcrumbSchema'

const startingPrice = config.dumpsters[0]?.pricing['10-day']

export const metadata = {
  title: `Book a Dumpster Online - From $${startingPrice} | ${config.businessName}`,
  description: `Book your dumpster rental online in under 2 minutes. Choose your size, drop a pin on the map for placement, pay securely, get same-day delivery in ${config.address.city}, IL and ${config.serviceTowns.length}+ Southern Illinois towns. From $${startingPrice}.`,
  alternates: {
    canonical: `${config.websiteUrl}/book`,
  },
  openGraph: {
    title: `Book a Dumpster Online — From $${startingPrice}, Same-Day Delivery`,
    description: `Online booking with map placement and instant payment. Serving ${config.address.city}, IL and ${config.serviceTowns.length}+ Southern Illinois towns. 10-day rentals from $${startingPrice}.`,
    url: `${config.websiteUrl}/book`,
    type: 'website',
    // OG image auto-generated by ./opengraph-image.jsx
  },
}

export default function BookLayout({ children }) {
  return (
    <>
      <BreadcrumbSchema items={[{ name: 'Book', path: '/book' }]} />
      {children}
    </>
  )
}
